// challenges/todo-list-vue/starter/solution.vue
<script setup lang="ts">
import { ref } from "vue";

const text = ref("");
const todos = ref<string[]>([]);

function addTodo() {
  throw new Error("TODO");
}
</script>

<template>
  <input v-model="text" aria-label="todo" />
  <button type="button" @click="addTodo">Add</button>
  <ul><li v-for="(t, i) in todos" :key="i">{{ t }}</li></ul>
</template>

// challenges/todo-list-react/starter/solution.tsx
import { useState } from "react";

export type Todo = { id: number; text: string; done: boolean };

export function TodoList() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [text, setText] = useState("");
  return (
    <div>
      <input aria-label="new todo" value={text} onChange={(e) => setText(e.target.value)} />
      <ul>{todos.map((t) => <li key={t.id}>{t.text}</li>)}</ul>
    </div>
  );
}
